### ISSUE TITLE
Folder Not Empty Makes Program Panic

### ISSUE THREAD

**Issue by JimLynchCodes** [XtremeDevX/delete#1]
Hi, I am using this code to delete a `.git` folder:

```rust
delete_folder(&format!("./cloned_repos/{}/.git", repo_name)).unwrap();
```

I does work, but my program outputs this scary panic message to the console:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 66, kind: DirectoryNotEmpty, message: "Directory not empty" }', src/bin/image_resizer/main.rs:40:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is there any way I can make it not panic? Something similar to adding the `-f` flag when running `rm -rf` in a unix shell?

thanks!

**Comment by JimLynchCodes** [comment]
I found the solution- use `delete_folder_all` instead. 👍

**Comment by suptejas** [comment]
Awesome, glad you were able to find a fix!

**Comment by suptejas** [comment]
Perhaps it would be useful to add this into the documentation - i'll try to work on this when I get a chance :)

**Comment by Krishna2323** [comment]
Thats awesome, it's fixed now.

**Comment by reecepm** [comment]
good work!
